[pytest]
# Автоматически определять асинхронные тесты (необязательно ставить маркер @pytest.mark.asyncio)
asyncio_mode=auto
# Создавать новый цикл событий для каждого теста для изоляции
asyncio_default_fixture_loop_scope=function

testpaths=tests
pythonpath=.